### PR TITLE
Styling/sign in

### PR DESCRIPTION
**Pull request by tauanlongaretti**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Change Status

- [X] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [X] Tested through running the server and making sure the component worked for all breakpoints

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by tauanlongaretti** [comment]
[Login Page - Styling](https://trello.com/c/cJUCxo97/46-login-page-styling)

**Comment by mikepadiernos** [comment]
The problem is that the form, dimmer, loader & divider still uses components from semantic UI. Will that remain?

**Comment by tauanlongaretti** [comment]
Joshua and I agreed that since the component was fully functioning and in fact had some nice aspects about it, we should use Tailwind for the styling and responsiveness only.

**Comment by mikepadiernos** [comment]
Ah ok that's fine. It will take a big overhaul to transition everything

**Pull request merged**
